name = "GGHJK Normal"
author = "Beard"
version = "2.7.9-hotfix"
description = "GGHJK Normal Modpack"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f78b0123d7bc5b1a133863a4e6c33b3457c510f9e608b1fbae4e638064830bcf"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.213"

[options]
acceptable-game-versions = []
datapack-folder = "world\\datapacks"
