name = "GGHJK Normal"
author = "Beard1425"
version = "3.4-beta.1-hotfix"
description = "GGHJK Normal Modpack"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6232f95448bd50ec34a6b7835b536077f8c4c8944bee6b03d6ce292cec469b09"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"

[options]
acceptable-game-versions = []
datapack-folder = "world\\datapacks"
