name = "GGHJK Normal"
author = "Beard"
version = "2.7.7"
description = "GGHJK Normal Modpack"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "983cec7c3d7f42a34c452acd81f881c5c633dae66e2b7c02092ed089525f33c5"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.213"

[options]
acceptable-game-versions = []
